site_name: coral_pytorch
site_url: http://raschka-research-group.github.io/coral_pytorch
site_author: Sebastian Raschka
site_description: coral_pytorch is a package implementing the CORAL PyTorch utilities.

repo_url: https://github.com/raschka-research-group/coral_pytorch

#include_search: true
#theme: yeti

docs_dir: docs
site_favicon: favicon.ico

# install via pip install mkdocs-material
theme: material

markdown_extensions:
  - pymdownx.highlight # syntax highlighting
  - pymdownx.superfences # syntax highlighting
  - tables
  - fenced_code
  - mdx_math:
      enable_dollar_delimiter: True # for use of inline $..$
extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS_HTML
  - mathjaxhelper.js
extra_css:
  - extra.css

copyright: Copyright &copy; 2020-2021 <a href="http://sebastianraschka.com">Sebastian Raschka</a>
#google_analytics: ['UA-38457794-3', 'raschka-research-group.github.io/pytorch_coral']

nav:
    - Home: index.md
    - Tutorials:
      - CORAL MNIST (image, CNN): tutorials/CORAL_mnist.md
      - CORN Cement (tabular, MLP): tutorials/CORAL_cement.md
      - CORN MNIST (image, CNN): tutorials/CORN_mnist.md
      - CORN Cement (tabular, MLP): tutorials/CORN_cement.md
    - API:
          - coral_pytorch.dataset: api_subpackages/coral_pytorch.dataset.md
          - coral_pytorch.layers: api_subpackages/coral_pytorch.layers.md
          - coral_pytorch.losses: api_subpackages/coral_pytorch.losses.md
    - Installation: installation.md
    - Changelog: changelog.md
    - Citing: citing.md
    - License: license.md
